-- MySQL Script generated by MySQL Workbench
-- Thu Nov 29 11:59:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `id` VARCHAR(45) NOT NULL,
  `civilite` VARCHAR(5) NOT NULL,
  `nom` VARCHAR(20) NOT NULL,
  `prenom` VARCHAR(20) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `complement_adresse` VARCHAR(45) NULL,
  `code_postal` INT NOT NULL,
  `ville` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `mot_de_passe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `nom`, `prenom`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Menu` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `id` INT NOT NULL,
  `nom_menu` VARCHAR(45) NULL,
  `avec_boisson` TINYINT(0) NOT NULL,
  `avec_salade` TINYINT(0) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pizza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pizza` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pizza` (
  `id` INT NOT NULL,
  `nom_pizza` VARCHAR(40) NOT NULL,
  `ingredient` VARCHAR(45) NOT NULL,
  `avec_menu` TINYINT NOT NULL DEFAULT 0,
  `Menu_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Menu_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Pizza_Menu1_idx` (`Menu_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pizza_Menu1`
    FOREIGN KEY (`Menu_id`)
    REFERENCES `mydb`.`Menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Une table par pizza différente comprenant :\nSon nom\nSes ingrédients\nSi avec menu';


-- -----------------------------------------------------
-- Table `mydb`.`Systeme_bancaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Systeme_bancaire` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Systeme_bancaire` (
  `id` INT NOT NULL,
  `client_id` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `code_banque` INT NOT NULL,
  `paiement_accepte` TINYINT(0) NOT NULL,
  `date_transaction` DATETIME NOT NULL,
  `client_nom` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `client_prenom` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`, `client_id`, `client_nom`, `client_prenom`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Systeme_bancaire_client_idx` (`client_id` ASC, `client_nom` ASC, `client_prenom` ASC) VISIBLE,
  CONSTRAINT `fk_Systeme_bancaire_client`
    FOREIGN KEY (`client_id` , `client_nom` , `client_prenom`)
    REFERENCES `mydb`.`client` (`id` , `nom` , `prenom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pizzaiolo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pizzaiolo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pizzaiolo` (
  `id` INT NOT NULL,
  `civilite` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `numero_securite_sociale` INT NOT NULL,
  `date_naissance` TIMESTAMP(1) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `complement_adresse` VARCHAR(45) NULL,
  `code_postal` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Pizzaiolo_Comptabilite1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`Comptabilite` (`commande_Pizzaiolo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`commande` ;

CREATE TABLE IF NOT EXISTS `mydb`.`commande` (
  `id` INT NOT NULL,
  `pizza(s)` INT NOT NULL,
  `menu` TINYINT(0) NOT NULL,
  `date` TIMESTAMP(1) NOT NULL,
  `avancement_commande_nom_pizza` INT NOT NULL,
  `Pizzaiolo_id` INT NOT NULL,
  `client_id` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `client_nom` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `client_prenom` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`, `Pizzaiolo_id`, `client_id`, `client_nom`, `client_prenom`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_commande_Pizzaiolo1_idx` (`Pizzaiolo_id` ASC) VISIBLE,
  INDEX `fk_commande_client1_idx` (`client_id` ASC, `client_nom` ASC, `client_prenom` ASC) VISIBLE,
  CONSTRAINT `fk_commande_Pizzaiolo1`
    FOREIGN KEY (`Pizzaiolo_id`)
    REFERENCES `mydb`.`Pizzaiolo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_client1`
    FOREIGN KEY (`client_id` , `client_nom` , `client_prenom`)
    REFERENCES `mydb`.`client` (`id` , `nom` , `prenom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pizzeria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pizzeria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pizzeria` (
  `id` INT NOT NULL,
  `numero_siret` INT NOT NULL,
  `civilite` VARCHAR(5) NOT NULL,
  `nomGerant` VARCHAR(20) NOT NULL,
  `nombre_employees` INT NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `complement_adresse` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`, `numero_siret`),
  UNIQUE INDEX `numero_siret_UNIQUE` (`numero_siret` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comptabilite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Comptabilite` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Comptabilite` (
  `Systeme_bancaire_id` INT NOT NULL,
  `Systeme_bancaire_client_id` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `client_id` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `client_nom` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `client_prenom` VARCHAR(20) NOT NULL,
  `commande_id` INT NOT NULL,
  `commande_Pizzaiolo_id` INT NOT NULL,
  `commande_client_id` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `Pizzeria_id` INT NOT NULL,
  `Pizzeria_numero_siret` INT NOT NULL,
  PRIMARY KEY (`client_id`, `client_nom`, `client_prenom`, `commande_id`, `commande_Pizzaiolo_id`, `commande_client_id`, `Pizzeria_id`, `Pizzeria_numero_siret`),
  INDEX `fk_Comptabilite_client1_idx` (`client_id` ASC, `client_nom` ASC, `client_prenom` ASC) VISIBLE,
  INDEX `fk_Comptabilite_commande1_idx` (`commande_id` ASC, `commande_Pizzaiolo_id` ASC, `commande_client_id` ASC) VISIBLE,
  INDEX `fk_Comptabilite_Pizzeria1_idx` (`Pizzeria_id` ASC, `Pizzeria_numero_siret` ASC) VISIBLE,
  UNIQUE INDEX `commande_Pizzaiolo_id_UNIQUE` (`commande_Pizzaiolo_id` ASC) VISIBLE,
  UNIQUE INDEX `client_id_UNIQUE` (`client_id` ASC) VISIBLE,
  UNIQUE INDEX `commande_id_UNIQUE` (`commande_id` ASC) VISIBLE,
  CONSTRAINT `fk_Comptabilite_Systeme_bancaire1`
    FOREIGN KEY (`Systeme_bancaire_id` , `Systeme_bancaire_client_id`)
    REFERENCES `mydb`.`Systeme_bancaire` (`id` , `client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comptabilite_client1`
    FOREIGN KEY (`client_id` , `client_nom` , `client_prenom`)
    REFERENCES `mydb`.`client` (`id` , `nom` , `prenom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comptabilite_commande1`
    FOREIGN KEY (`commande_id` , `commande_Pizzaiolo_id` , `commande_client_id`)
    REFERENCES `mydb`.`commande` (`id` , `Pizzaiolo_id` , `client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comptabilite_Pizzeria1`
    FOREIGN KEY (`Pizzeria_id` , `Pizzeria_numero_siret`)
    REFERENCES `mydb`.`Pizzeria` (`id` , `numero_siret`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`facture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`facture` ;

CREATE TABLE IF NOT EXISTS `mydb`.`facture` (
  `Id` VARCHAR(45) NOT NULL,
  `client_nom` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `client_prenom` VARCHAR(20) NOT NULL,
  `montant_facture` INT NOT NULL,
  `reglee` TINYINT(0) NOT NULL DEFAULT 0,
  `Comptabilite_client_id` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `Comptabilite_client_nom` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `Comptabilite_client_prenom` VARCHAR(20) NOT NULL,
  `Comptabilite_commande_id` INT NOT NULL,
  `Comptabilite_commande_Pizzaiolo_id` INT NOT NULL,
  `Comptabilite_commande_client_id` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `Comptabilite_Pizzeria_id` INT NOT NULL,
  `Comptabilite_Pizzeria_numero_siret` INT NOT NULL,
  PRIMARY KEY (`Id`, `client_nom`, `client_prenom`),
  UNIQUE INDEX `ID_UNIQUE` (`Id` ASC) VISIBLE,
  INDEX `fk_facture_Comptabilite1_idx` (`Comptabilite_client_id` ASC, `Comptabilite_client_nom` ASC, `Comptabilite_client_prenom` ASC, `Comptabilite_commande_id` ASC, `Comptabilite_commande_Pizzaiolo_id` ASC, `Comptabilite_commande_client_id` ASC, `Comptabilite_Pizzeria_id` ASC, `Comptabilite_Pizzeria_numero_siret` ASC) VISIBLE,
  CONSTRAINT `fk_facture_Comptabilite1`
    FOREIGN KEY (`Comptabilite_client_id` , `Comptabilite_client_nom` , `Comptabilite_client_prenom` , `Comptabilite_commande_id` , `Comptabilite_commande_Pizzaiolo_id` , `Comptabilite_commande_client_id` , `Comptabilite_Pizzeria_id` , `Comptabilite_Pizzeria_numero_siret`)
    REFERENCES `mydb`.`Comptabilite` (`client_id` , `client_nom` , `client_prenom` , `commande_id` , `commande_Pizzaiolo_id` , `commande_client_id` , `Pizzeria_id` , `Pizzeria_numero_siret`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avancement_commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`avancement_commande` ;

CREATE TABLE IF NOT EXISTS `mydb`.`avancement_commande` (
  `id` INT NOT NULL,
  `commande_recue` TINYINT(0) NOT NULL,
  `commande_en_preparation` TINYINT(0) NOT NULL,
  `commande_finie` TINYINT(0) NOT NULL,
  `commande_livraison` TINYINT(0) NOT NULL,
  `commande_id` INT NOT NULL,
  PRIMARY KEY (`id`, `commande_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_avancement_commande_commande1_idx` (`commande_id` ASC) VISIBLE,
  CONSTRAINT `fk_avancement_commande_commande1`
    FOREIGN KEY (`commande_id`)
    REFERENCES `mydb`.`commande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stock_Ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Stock_Ingredients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Stock_Ingredients` (
  `Ingredient_1` INT NULL,
  `Ingredient_2` INT NULL,
  `ingredient_3` INT NULL,
  `ingredient_4` INT NULL,
  `ingredient_5` INT NULL,
  `ingredient_6` INT NULL,
  `ingredient_7` INT NULL,
  `ingredient_8` INT NULL,
  `ingredient_9` INT NULL,
  `Pizzaiolo_id` INT NOT NULL,
  PRIMARY KEY (`Pizzaiolo_id`),
  CONSTRAINT `fk_Stock_Ingredients_Pizzaiolo1`
    FOREIGN KEY (`Pizzaiolo_id`)
    REFERENCES `mydb`.`Pizzaiolo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pizzaiolo_has_avancement_commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pizzaiolo_has_avancement_commande` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pizzaiolo_has_avancement_commande` (
  `Pizzaiolo_id` INT NOT NULL,
  `avancement_commande_id` INT NOT NULL,
  `avancement_commande_commande_id` INT NOT NULL,
  PRIMARY KEY (`Pizzaiolo_id`, `avancement_commande_id`, `avancement_commande_commande_id`),
  INDEX `fk_Pizzaiolo_has_avancement_commande_avancement_commande1_idx` (`avancement_commande_id` ASC, `avancement_commande_commande_id` ASC) VISIBLE,
  INDEX `fk_Pizzaiolo_has_avancement_commande_Pizzaiolo1_idx` (`Pizzaiolo_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pizzaiolo_has_avancement_commande_Pizzaiolo1`
    FOREIGN KEY (`Pizzaiolo_id`)
    REFERENCES `mydb`.`Pizzaiolo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pizzaiolo_has_avancement_commande_avancement_commande1`
    FOREIGN KEY (`avancement_commande_id` , `avancement_commande_commande_id`)
    REFERENCES `mydb`.`avancement_commande` (`id` , `commande_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pizzaiolo_has_Pizza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pizzaiolo_has_Pizza` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pizzaiolo_has_Pizza` (
  `Pizzaiolo_id` INT NOT NULL,
  `Pizza_id` INT NOT NULL,
  PRIMARY KEY (`Pizzaiolo_id`, `Pizza_id`),
  INDEX `fk_Pizzaiolo_has_Pizza_Pizza1_idx` (`Pizza_id` ASC) VISIBLE,
  INDEX `fk_Pizzaiolo_has_Pizza_Pizzaiolo1_idx` (`Pizzaiolo_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pizzaiolo_has_Pizza_Pizzaiolo1`
    FOREIGN KEY (`Pizzaiolo_id`)
    REFERENCES `mydb`.`Pizzaiolo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pizzaiolo_has_Pizza_Pizza1`
    FOREIGN KEY (`Pizza_id`)
    REFERENCES `mydb`.`Pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pizzaiolo_has_Menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pizzaiolo_has_Menu` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pizzaiolo_has_Menu` (
  `Pizzaiolo_id` INT NOT NULL,
  `Menu_id` INT NOT NULL,
  PRIMARY KEY (`Pizzaiolo_id`, `Menu_id`),
  INDEX `fk_Pizzaiolo_has_Menu_Menu1_idx` (`Menu_id` ASC) VISIBLE,
  INDEX `fk_Pizzaiolo_has_Menu_Pizzaiolo1_idx` (`Pizzaiolo_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pizzaiolo_has_Menu_Pizzaiolo1`
    FOREIGN KEY (`Pizzaiolo_id`)
    REFERENCES `mydb`.`Pizzaiolo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pizzaiolo_has_Menu_Menu1`
    FOREIGN KEY (`Menu_id`)
    REFERENCES `mydb`.`Menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
